[package]
name = "scraper"
version = "0.9.0"

description = "HTML parsing and querying with CSS selectors"
keywords = ["html", "css", "selector", "scraping"]

authors = [
    "Curtis McEnroe <june@causal.agency>",
    "Vivek Kushwaha <yoursvivek@gmail.com>",
]
license = "ISC"

repository = "https://github.com/programble/scraper"
readme = "README.md"

[dependencies]
cssparser = "0.25.2"
ego-tree = "0.6.0"
getopts = "0.2.18"
html5ever = "0.22.5"
matches = "0.1.8"
selectors = "0.21.0"
smallvec = "0.6.7"
tendril = "0.4.1"
